import { describe, it, expect } from 'vitest';

describe('POST /api/posts - Contract Test', () => {
    const API_URL = 'http://localhost:3000/api/posts';

    it('should create a new post with valid data and authentication', async () => {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer mock-token',
            },
            body: JSON.stringify({
                content: 'Exciting new post content generated by AI!',
                status: 'DRAFT',
            }),
        });

        expect(response.status).toBe(201);
        const data = await response.json();
        expect(data).toHaveProperty('post');
        expect(data.post).toHaveProperty('id');
        expect(data.post.content).toBe('Exciting new post content generated by AI!');
        expect(data.post.status).toBe('DRAFT');
        expect(data.post).toHaveProperty('userId');
        expect(data.post).toHaveProperty('createdAt');
    });

    it('should return 401 without authentication', async () => {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                content: 'Test post',
            }),
        });

        expect(response.status).toBe(401);
        const data = await response.json();
        expect(data).toHaveProperty('error', 'Authentication required');
    });

    it('should return 400 for empty content', async () => {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer mock-token',
            },
            body: JSON.stringify({
                content: '',
            }),
        });

        expect(response.status).toBe(400);
        const data = await response.json();
        expect(data).toHaveProperty('error', 'Content cannot be empty');
    });

    it('should default status to DRAFT if not provided', async () => {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                Authorization: 'Bearer mock-token',
            },
            body: JSON.stringify({
                content: 'Post without status',
            }),
        });

        expect(response.status).toBe(201);
        const data = await response.json();
        expect(data.post.status).toBe('DRAFT');
    });
});
